services:
  v1-report:
    restart: always
    image: ${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:latest
    container_name: v1-report
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
        - NODE_ENV=${ENV}
        - MONGODB_URI=${MONGODB_URI}
        - JWT_SECRET=${JWT_SECRET}
        - ENC_KEY=${ENC_KEY}
        - AWS_REGION=${AWS_REGION}
        - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /var/log/V1_Report:/app/logs
      - ${HOME}/.aws:/root/.aws
    network_mode: host